# Generated by Django 5.2 on 2025-04-24 19:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='profissionais',
            field=models.ManyToManyField(limit_choices_to={'tipo': 'PROFISSIONAL'}, related_name='servicos', to=settings.AUTH_USER_MODEL),
        ),
    ]
