# Generated by Django 5.2 on 2025-05-26 22:18

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_alter_servico_duracao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='duracao',
            field=models.DurationField(default=datetime.timedelta(seconds=1800), help_text='Duração do serviço (ex: 0:30:00 para 30 min, 1:30:00 para 1h30).'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='preco',
            field=models.DecimalField(decimal_places=2, help_text='Preço do serviço (em reais).', max_digits=8),
        ),
        migrations.AlterField(
            model_name='servico',
            name='profissionais',
            field=models.ManyToManyField(help_text='Profissionais habilitados para realizar este serviço.', limit_choices_to={'tipo': 'PROFISSIONAL'}, related_name='servicos', to=settings.AUTH_USER_MODEL),
        ),
    ]
