# Generated by Django 5.2 on 2025-04-24 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('servicos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'tipo': 'CLIENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_como_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='profissional',
            field=models.ForeignKey(limit_choices_to={'tipo': 'PROFISSIONAL'}, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_como_profissional', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.servico'),
        ),
        migrations.AddField(
            model_name='horarioexpediente',
            name='profissional',
            field=models.ForeignKey(limit_choices_to={'tipo': 'PROFISSIONAL'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
