# Generated by Django 5.2 on 2025-04-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='horarioexpediente',
            options={},
        ),
        migrations.AddField(
            model_name='horarioexpediente',
            name='horarios',
            field=models.ManyToManyField(related_name='expedientes', to='agenda.horario'),
        ),
    ]
