# Generated by Django 5.2 on 2025-05-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_horario_alter_horarioexpediente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='duracao_personalizada',
            field=models.PositiveIntegerField(blank=True, help_text='Duração personalizada em minutos para este agendamento (opcional).', null=True),
        ),
    ]
