# Generated by Django 5.2 on 2025-05-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_agendamento_duracao_personalizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='recorrencia_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
